<?php
namespace backend\modules\permission\models;

use Yii;
use yii\helpers\Inflector;

class Role extends \dektrium\rbac\models\Role
{
    public function attributeLabels()
    {
        $labels =  parent::attributeLabels();
        $labels['description'] = Yii::t('app', 'Nazwa');
        $labels['superuser'] = Yii::t('app', 'Superuser');
        return $labels;
    }

    public function beforeValidate()
    {
        $this->name = Inflector::slug($this->description);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}