<?php

namespace common\models;

use Yii;
use \common\models\base\InvoicePaymentHistory as BaseInvoicePaymentHistory;

/**
 * This is the model class for table "invoice_payment_history".
 */
class InvoicePaymentHistory extends BaseInvoicePaymentHistory
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestampBehavior'] = [
            'class' => \yii\behaviors\TimestampBehavior::className(),
            'createdAtAttribute' => 'create_time',
            'updatedAtAttribute' => 'update_time',
            'value' => new \yii\db\Expression('NOW()'),
        ];
        return $behaviors;
    }

    public function beforeValidate()
    {
        $this->amount = str_replace(' ', '', $this->amount);
        if (empty($this->date))
        {
            $this->date = date('Y-m-d');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
