<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "addon_rate".
 *
 * @property integer $id
 * @property string $amount
 * @property integer $level
 * @property string $create_time
 * @property string $update_time
 * @property integer $period
 * @property string $name
 *
 * @property \common\models\AddonRateRole[] $addonRateRoles
 * @property \common\models\UserAddonRate[] $userAddonRates
 * @property \common\models\UserEventRole[] $roles
 * @property string $aliasModel
 */
abstract class AddonRate extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'addon_rate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['amount'], 'required'],
            [['amount'], 'number'],
            [['level', 'period'], 'integer'],
            [['create_time', 'update_time', 'roles'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['amount', 'level', 'period'], 'unique', 'targetAttribute' => ['amount', 'level', 'period'], 'message' => Yii::t('app', 'Kombinacja stawki, poziomu eventu i okresu naliczania została już wcześniej stworzona.')]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'amount' => Yii::t('app', 'Stawka'),
            'level' => Yii::t('app', 'Poziom eventu'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'period' => Yii::t('app', 'Okres naliczania'),
            'name' => Yii::t('app', 'Nazwa'),
            'roleIds' => Yii::t('app', 'Role'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserAddonRates()
    {
        return $this->hasMany(\common\models\UserAddonRate::className(), ['rate_id' => 'id']);
    }

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getAddonRateRoles()
	{
		return $this->hasMany(\common\models\AddonRateRole::className(), ['addon_rate_id' => 'id']);
	}


	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getRoles()
	{
		return $this->hasMany(\common\models\UserEventRole::className(), ['id' => 'role_id'])->viaTable('addon_rate_role', ['addon_rate_id' => 'id']);
	}

}
