<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "addon_rate_role".
 *
 * @property integer $id
 * @property integer $addon_rate_id
 * @property integer $role_id
 *
 * @property \common\models\AddonRate $addonRate
 * @property \common\models\UserEventRole $role
 * @property string $aliasModel
 */
abstract class AddonRateRole extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'addon_rate_role';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['addon_rate_id', 'role_id'], 'required'],
            [['addon_rate_id', 'role_id'], 'integer'],
            [['addon_rate_id'], 'exist', 'skipOnError' => true, 'targetClass' => AddonRate::className(), 'targetAttribute' => ['addon_rate_id' => 'id']],
            [['role_id'], 'exist', 'skipOnError' => true, 'targetClass' => UserEventRole::className(), 'targetAttribute' => ['role_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'addon_rate_id' => Yii::t('app', 'ID dodatku'),
            'role_id' => Yii::t('app', 'ID roli'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddonRate()
    {
        return $this->hasOne(\common\models\AddonRate::className(), ['id' => 'addon_rate_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRole()
    {
        return $this->hasOne(\common\models\UserEventRole::className(), ['id' => 'role_id']);
    }




}
