<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "attachment".
 *
 * @property integer $id
 * @property string $filename
 * @property string $extension
 * @property integer $type
 * @property integer $status
 * @property string $content
 * @property string $create_time
 * @property string $update_time
 * @property string $info
 * @property integer $event_id
 * @property string $mime_type
 * @property string $base_name
 * @property integer $public
 *
 * @property \common\models\Event $event
 * @property string $aliasModel
 */
abstract class Attachment extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'attachment';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'status', 'event_id', 'public'], 'integer'],
            [['content', 'info'], 'string'],
            [['create_time', 'update_time'], 'safe'],
            [['event_id'], 'required'],
            [['filename', 'extension', 'mime_type', 'base_name'], 'string', 'max' => 255],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'filename' => Yii::t('app', 'Nazwa pliku'),
            'extension' => Yii::t('app', 'Rozszerzenie'),
            'type' => Yii::t('app', 'Typ'),
            'status' => Yii::t('app', 'Status'),
            'content' => Yii::t('app', 'Zawartość'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'info' => Yii::t('app', 'Info'),
            'event_id' => Yii::t('app', 'Wydarzenie'),
            'mime_type' => Yii::t('app', 'Typ Mime'),
            'base_name' => Yii::t('app', 'Nazwa podstawowa'),
            'public' => Yii::t('app', 'Publiczny'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }




}
