<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "customer_discount_category".
 *
 * @property integer $customer_discount_id
 * @property integer $category_id
 *
 * @property \common\models\CustomerDiscount $customerDiscount
 * @property \common\models\GearCategory $category
 * @property string $aliasModel
 */
abstract class CustomerDiscountCategory extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer_discount_category';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_discount_id', 'category_id'], 'required'],
            [['customer_discount_id', 'category_id'], 'integer'],
            [['customer_discount_id'], 'exist', 'skipOnError' => true, 'targetClass' => CustomerDiscount::className(), 'targetAttribute' => ['customer_discount_id' => 'id']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearCategory::className(), 'targetAttribute' => ['category_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'customer_discount_id' => Yii::t('app', 'ID rabatu klienta'),
            'category_id' => Yii::t('app', 'ID kategorii'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomerDiscount()
    {
        return $this->hasOne(\common\models\CustomerDiscount::className(), ['id' => 'customer_discount_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\GearCategory::className(), ['id' => 'category_id']);
    }




}
