<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "customer_discount_customer".
 *
 * @property integer $customer_discount_id
 * @property integer $customer_id
 *
 * @property \common\models\Customer $customer
 * @property \common\models\CustomerDiscount $customerDiscount
 * @property string $aliasModel
 */
abstract class CustomerDiscountCustomer extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer_discount_customer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_discount_id', 'customer_id'], 'required'],
            [['customer_discount_id', 'customer_id'], 'integer'],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Customer::className(), 'targetAttribute' => ['customer_id' => 'id']],
            [['customer_discount_id'], 'exist', 'skipOnError' => true, 'targetClass' => CustomerDiscount::className(), 'targetAttribute' => ['customer_discount_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'customer_discount_id' => Yii::t('app', 'ID rabatu klienta'),
            'customer_id' => Yii::t('app', 'ID klienta'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\common\models\Customer::className(), ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomerDiscount()
    {
        return $this->hasOne(\common\models\CustomerDiscount::className(), ['id' => 'customer_discount_id']);
    }




}
