<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "department".
 *
 * @property integer $id
 * @property string $name
 * @property integer $status
 * @property integer $type
 * @property string $create_time
 * @property string $update_time
 * @property string $color
 *
 * @property \common\models\CalendarUserFilter[] $calendarUserFilters
 * @property \common\models\EventDepartment[] $eventDepartments
 * @property \common\models\Event[] $events
 * @property \common\models\EventExpense[] $eventExpenses
 * @property \common\models\EventUserWorkingTime[] $eventUserWorkingTimes
 * @property \common\models\OfferCustomItems[] $offerCustomItems
 * @property \common\models\UserDepartment[] $userDepartments
 * @property \common\models\User[] $users
 * @property string $aliasModel
 */
abstract class Department extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'department';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status', 'type'], 'integer'],
            [['create_time', 'update_time'], 'safe'],
            [['name', 'color'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nazwa'),
            'status' => Yii::t('app', 'Status'),
            'type' => Yii::t('app', 'Typ'),
            'create_time' => Yii::t('app', 'Dodano'),
            'update_time' => Yii::t('app', 'Edytowano'),
            'color' => Yii::t('app', 'Kolor'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCalendarUserFilters()
    {
        return $this->hasMany(\common\models\CalendarUserFilter::className(), ['department' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventDepartments()
    {
        return $this->hasMany(\common\models\EventDepartment::className(), ['department_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(\common\models\Event::className(), ['id' => 'event_id'])->viaTable('event_department', ['department_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventExpenses()
    {
        return $this->hasMany(\common\models\EventExpense::className(), ['department_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventUserWorkingTimes()
    {
        return $this->hasMany(\common\models\EventUserWorkingTime::className(), ['department_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOfferCustomItems()
    {
        return $this->hasMany(\common\models\OfferCustomItems::className(), ['department_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserDepartments()
    {
        return $this->hasMany(\common\models\UserDepartment::className(), ['department_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(\common\models\User::className(), ['id' => 'user_id'])->viaTable('user_department', ['department_id' => 'id']);
    }




}
