<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "event_user_planned_wroking_time".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $event_id
 * @property string $start_time
 * @property string $end_time
 *
 * @property \common\models\User $user
 * @property \common\models\Event $event
 * @property string $aliasModel
 */
abstract class EventUserPlannedWrokingTime extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event_user_planned_wroking_time';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'event_id', 'start_time', 'end_time'], 'required'],
            [['user_id', 'event_id'], 'integer'],
            [['start_time', 'end_time'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'ID użytkownika'),
            'event_id' => Yii::t('app', 'ID wydarzenia'),
            'start_time' => Yii::t('app', 'Początek'),
            'end_time' => Yii::t('app', 'Koniec'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventSchedule()
    {
        return $this->hasOne(\common\models\EventSchedule::className(), ['id' => 'event_schedule_id']);
    }
        /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoles()
    {
        return $this->hasMany(\common\models\EventUserRole::className(), ['working_hours_id' => 'id']);
    }




}
