<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "event_working_time_role".
 *
 * @property integer $working_time_id
 * @property integer $role_id
 * @property string $create_time
 * @property string $update_time
 *
 * @property \common\models\EventUserWorkingTime $workingTime
 * @property \common\models\UserEventRole $role
 * @property string $aliasModel
 */
abstract class EventWorkingTimeRole extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event_working_time_role';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['working_time_id', 'role_id'], 'required'],
            [['working_time_id', 'role_id'], 'integer'],
            [['create_time', 'update_time'], 'safe'],
            [['role_id', 'working_time_id'], 'unique', 'targetAttribute' => ['role_id', 'working_time_id'], 'message' => 'The combination of Working Time ID and Role ID has already been taken.'],
            [['working_time_id'], 'exist', 'skipOnError' => true, 'targetClass' => EventUserWorkingTime::className(), 'targetAttribute' => ['working_time_id' => 'id']],
            [['role_id'], 'exist', 'skipOnError' => true, 'targetClass' => UserEventRole::className(), 'targetAttribute' => ['role_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'working_time_id' => Yii::t('app', 'ID czasu pracy'),
            'role_id' => Yii::t('app', 'ID roli'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkingTime()
    {
        return $this->hasOne(\common\models\EventUserWorkingTime::className(), ['id' => 'working_time_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRole()
    {
        return $this->hasOne(\common\models\UserEventRole::className(), ['id' => 'role_id']);
    }




}
