<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "event_message".
 *
 * @property integer $id
 * @property integer $event_id
 * @property string $title
 * @property string $content
 * @property string $create_time
 * @property string $update_time
 * @property integer $push
 * @property integer $sms
 * @property integer $email
 * @property string $recipients_push
 * @property string $recipients_sms
 * @property string $recipients_email
 * @property string $sent_time
 * @property integer $type
 * @property integer $status
 *
 * @property \common\models\Event $event
 * @property string $aliasModel
 */
abstract class EventMessage extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event_message';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event_id', 'content'], 'required'],
            [['event_id', 'push', 'sms', 'email', 'type', 'status'], 'integer'],
            [['content', 'recipients_push', 'recipients_sms', 'recipients_email'], 'string'],
            [['create_time', 'update_time', 'sent_time'], 'safe'],
            [['title'], 'string', 'max' => 255],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'event_id' => Yii::t('app', 'Wydarzenie'),
            'title' => Yii::t('app', 'Tytuł'),
            'content' => Yii::t('app', 'Treść'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'push' => Yii::t('app', 'Push'),
            'sms' => Yii::t('app', 'SMS'),
            'email' => Yii::t('app', 'Email'),
            'recipients_push' => Yii::t('app', 'Odbiorcy push'),
            'recipients_sms' => Yii::t('app', 'Odbiorcy sms'),
            'recipients_email' => Yii::t('app', 'Odbiorcy email'),
            'sent_time' => Yii::t('app', 'Czas wysłania'),
            'type' => Yii::t('app', 'Typ'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }




}
