<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "event_outer_gear_item".
 *
 * @property integer $event_id
 * @property integer $outer_gear_item_id
 * @property integer $quantity
 * @property integer $discount
 * @property string $start_time
 * @property string $end_time
 * @property integer $type
 *
 * @property \common\models\Event $event
 * @property \common\models\OuterGearItem $outerGearItem
 * @property string $aliasModel
 */
abstract class EventOuterGearItem extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event_outer_gear_item';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event_id', 'outer_gear_item_id'], 'required'],
            [['event_id', 'outer_gear_item_id', 'quantity', 'discount', 'type'], 'integer'],
            [['start_time', 'end_time'], 'safe'],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']],
            [['outer_gear_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => OuterGearItem::className(), 'targetAttribute' => ['outer_gear_item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'event_id' => Yii::t('app','ID wydarzenia'),
            'outer_gear_item_id' => Yii::t('app','ID sprzętu zewnętrznego'),
            'quantity' => Yii::t('app','Liczba'),
            'discount' => Yii::t('app','Rabat'),
            'start_time' => Yii::t('app','Początek'),
            'end_time' => Yii::t('app','Koniec'),
            'type' => Yii::t('app','Typ'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOuterGearItem()
    {
        return $this->hasOne(\common\models\OuterGearItem::className(), ['id' => 'outer_gear_item_id']);
    }




}
