<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "event_finance".
 *
 * @property integer $id
 * @property integer $event_id
 * @property string $provision
 * @property integer $project_done
 * @property integer $invoice_issued
 * @property integer $invoice_sent
 * @property string $invoice_number
 * @property integer $status
 * @property integer $type
 * @property string $create_time
 * @property string $update_time
 *
 * @property \common\models\Event $event
 * @property string $aliasModel
 */
abstract class EventFinance extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event_finance';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event_id'], 'required'],
            [['event_id', 'project_done', 'invoice_issued', 'invoice_sent', 'status', 'type'], 'integer'],
            [['provision'], 'number'],
            [['create_time', 'update_time'], 'safe'],
            [['invoice_number'], 'string', 'max' => 255],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app','ID'),
            'event_id' => Yii::t('app','ID wydarzenia'),
            'provision' => Yii::t('app','Procent'),
            'project_done' => Yii::t('app','Projekt rozliczony'),
            'invoice_issued' => Yii::t('app','Faktura wystawiona'),
            'invoice_sent' => Yii::t('app','Faktura wysłana'),
            'invoice_number' => Yii::t('app','Numer faktury'),
            'status' => Yii::t('app','Status'),
            'type' => Yii::t('app','Typ'),
            'create_time' => Yii::t('app','Stworzono'),
            'update_time' => Yii::t('app','Zaktualizowano'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }




}
