<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "event_vehicle_working_hours".
 *
 * @property integer $id
 * @property integer $vehicle_id
 * @property integer $event_id
 * @property string $start_time
 * @property string $end_time
 *
 * @property \common\models\Vehicle $vehicle
 * @property \common\models\Event $event
 * @property string $aliasModel
 */
abstract class EventVehicleWorkingHours extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event_vehicle_working_hours';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vehicle_id', 'event_id', 'start_time', 'end_time'], 'required'],
            [['vehicle_id', 'event_id'], 'integer'],
            [['start_time', 'end_time'], 'safe'],
            [['vehicle_id'], 'exist', 'skipOnError' => true, 'targetClass' => Vehicle::className(), 'targetAttribute' => ['vehicle_id' => 'id']],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'vehicle_id' => Yii::t('app', 'ID pojazdu'),
            'event_id' => Yii::t('app', 'ID wydarzenia'),
            'start_time' => Yii::t('app', 'Początek'),
            'end_time' => Yii::t('app', 'Koniec'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicle()
    {
        return $this->hasOne(\common\models\Vehicle::className(), ['id' => 'vehicle_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicleModel()
    {
        return $this->hasOne(\common\models\VehicleModel::className(), ['id' => 'vehicle_model_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventSchedule()
    {
        return $this->hasOne(\common\models\EventSchedule::className(), ['id' => 'event_schedule_id']);
    }


}
