<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "expense_event".
 *
 * @property integer $expense_id
 * @property integer $event_id
 *
 * @property \common\models\Expense $expense
 * @property \common\models\Event $event
 * @property string $aliasModel
 */
abstract class ExpenseEvent extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'expense_event';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['expense_id', 'event_id'], 'required'],
            [['expense_id', 'event_id'], 'integer'],
            [['expense_id', 'event_id'], 'unique', 'targetAttribute' => ['expense_id', 'event_id'], 'message' => 'The combination of Expense ID and Event ID has already been taken.'],
            [['expense_id'], 'exist', 'skipOnError' => true, 'targetClass' => Expense::className(), 'targetAttribute' => ['expense_id' => 'id']],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'expense_id' => Yii::t('app', 'ID wydatku'),
            'event_id' => Yii::t('app', 'ID wydarzenia'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExpense()
    {
        return $this->hasOne(\common\models\Expense::className(), ['id' => 'expense_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }




}
