<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;

/**
 * This is the base-model class for table "expense_payment_history".
 *
 * @property integer $id
 * @property integer $expense_id
 * @property string $amount
 * @property string $date
 * @property string $create_time
 * @property string $update_time
 * @property integer $creator_id
 *
 * @property \common\models\User $creator
 * @property \common\models\Expense $expense
 * @property string $aliasModel
 */
abstract class ExpensePaymentHistory extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'expense_payment_history';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'creator_id',
                'updatedByAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['expense_id'], 'required'],
            [['expense_id'], 'integer'],
            [['amount'], 'number'],
            [['date', 'create_time', 'update_time', 'payment_method'], 'safe'],
            [['creator_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['creator_id' => 'id']],
            [['expense_id'], 'exist', 'skipOnError' => true, 'targetClass' => Expense::className(), 'targetAttribute' => ['expense_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'expense_id' => Yii::t('app', 'Faktura'),
            'creator_id' => Yii::t('app', 'Wprowadził'),
            'amount' => Yii::t('app', 'Kwota'),
            'date' => Yii::t('app', 'Data'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreator()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'creator_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExpense()
    {
        return $this->hasOne(\common\models\Expense::className(), ['id' => 'expense_id']);
    }




}
