<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "expense_content".
 *
 * @property integer $id
 * @property integer $expense_id
 * @property integer $external_id
 * @property string $name
 * @property string $classification
 * @property string $unit
 * @property string $count
 * @property string $price
 * @property string $discount
 * @property integer $discount_percent
 * @property string $netto
 * @property string $brutto
 * @property string $tax
 * @property string $vat
 * @property string $lumpcode
 * @property string $create_time
 * @property string $update_time
 * @property integer $item_id
 * @property string $item_class
 * @property string $item_tmp_name
 * @property integer $event_expense_id
 * @property integer $type
 * @property string $description
 *
 * @property \common\models\Expense $expense
 * @property \common\models\EventExpense $eventExpense
 * @property string $aliasModel
 */
abstract class ExpenseContent extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'expense_content';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['expense_id', 'external_id', 'discount_percent', 'item_id', 'event_expense_id', 'type'], 'integer'],
            [['name'], 'required'],
            [['count', 'price', 'discount', 'netto', 'brutto', 'tax', 'vat'], 'number'],
            [['create_time', 'update_time'], 'safe'],
            [['description'], 'string'],
            [['name', 'classification', 'unit', 'lumpcode', 'item_class', 'item_tmp_name'], 'string', 'max' => 255],
            [['expense_id'], 'exist', 'skipOnError' => true, 'targetClass' => Expense::className(), 'targetAttribute' => ['expense_id' => 'id']],
            [['event_expense_id'], 'exist', 'skipOnError' => true, 'targetClass' => EventExpense::className(), 'targetAttribute' => ['event_expense_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'expense_id' => Yii::t('app', 'ID wydatku'),
            'external_id' => Yii::t('app', 'ID zewnętrzne'),
            'name' => Yii::t('app', 'Nazwa'),
            'classification' => Yii::t('app', 'PKWiU'),
            'unit' => Yii::t('app', 'Jednostka'),
            'count' => Yii::t('app', 'Ilość'),
            'price' => Yii::t('app', 'Cena netto'),
            'discount' => Yii::t('app', 'Rabat?'),
            'discount_percent' => Yii::t('app', 'Rabat %'),
            'netto' => Yii::t('app', 'Wartość netto'),
            'brutto' => Yii::t('app', 'Wartość brutto'),
            'tax' => Yii::t('app', 'Wartość VAT'),
            'vat' => Yii::t('app', 'Stawka Vat'),
            'lumpcode' => Yii::t('app', 'Stawka ryczałtu'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'item_id' => Yii::t('app', 'ID przedmiotu'),
            'item_class' => Yii::t('app', 'Klasa przedmiotu'),
            'item_tmp_name' => Yii::t('app', 'Nazwa'),
            'event_expense_id' => Yii::t('app', 'Koszt'),
            'type' => Yii::t('app', 'Typ'),
            'description' => Yii::t('app', 'Opis'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExpense()
    {
        return $this->hasOne(\common\models\Expense::className(), ['id' => 'expense_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventExpense()
    {
        return $this->hasOne(\common\models\EventExpense::className(), ['id' => 'event_expense_id']);
    }




}
