<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "gear_history".
 *
 * @property integer $id
 * @property string $date_time
 * @property string $info
 * @property string $create_time
 * @property string $update_time
 * @property string $category
 * @property integer $gear_id
 * @property integer $type
 * @property integer $status
 *
 * @property \common\models\Gear $gear
 * @property string $aliasModel
 */
abstract class GearHistory extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gear_history';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_time', 'create_time', 'update_time'], 'safe'],
            [['info'], 'string'],
            [['gear_id', 'type', 'status'], 'integer'],
            [['category'], 'string', 'max' => 255],
            [['gear_id'], 'exist', 'skipOnError' => true, 'targetClass' => Gear::className(), 'targetAttribute' => ['gear_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'date_time' => Yii::t('app', 'Data i godzina'),
            'info' => Yii::t('app', 'Info'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'category' => Yii::t('app', 'Kategoria'),
            'gear_id' => Yii::t('app', 'ID modelu'),
            'type' => Yii::t('app', 'Typ'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGear()
    {
        return $this->hasOne(\common\models\Gear::className(), ['id' => 'gear_id']);
    }




}
