<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "gear_service".
 *
 * @property integer $id
 * @property integer $gear_item_id
 * @property string $description
 * @property string $create_time
 * @property string $update_time
 * @property string $status_time
 * @property integer $status
 * @property integer $type
 * @property string $info
 *
 * @property \common\models\GearItem $gearItem
 * @property string $aliasModel
 */
abstract class GearService extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gear_service';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gear_item_id'], 'required'],
            [['gear_item_id', 'status', 'type', 'quantity', 'priority', 'warehouse_from', 'warehouse_to'], 'integer'],
            [['description', 'info'], 'string'],
            [['create_time', 'update_time', 'status_time', 'deadline'], 'safe'],
            [['gear_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearItem::className(), 'targetAttribute' => ['gear_item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'gear_item_id' => Yii::t('app', 'Sprzęt'),
            'description' => Yii::t('app', 'Opis usterki'),
            'create_time' => Yii::t('app', 'Dodano'),
            'update_time' => Yii::t('app', 'Aktualizacja'),
            'status_time' => Yii::t('app', 'Zmiana statusu'),
            'status' => Yii::t('app', 'Status'),
            'type' => Yii::t('app', 'Typ'),
            'info' => Yii::t('app', 'Informacja'),
            'quantity' => Yii::t('app', 'Liczba sztuk'),
            'priority' => Yii::t('app', 'Priorytet'),
            'deadline' => Yii::t('app', 'Deadline'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGearItem()
    {
        return $this->hasOne(\common\models\GearItem::className(), ['id' => 'gear_item_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServiceStatus()
    {
        return $this->hasOne(\common\models\GearServiceStatut::className(), ['id' => 'status']);
    }


}
