<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "gear_company".
 *
 * @property integer $id
 * @property string $name
 * @property string $create_time
 * @property string $update_time
 *
 * @property \common\models\GearModel[] $gearModels
 * @property string $aliasModel
 */
abstract class GearCompany extends \common\components\BaseActiveRecord
{


    public static function getDb() {
        return Yii::$app->db2;
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gear_company';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['create_time', 'update_time'], 'safe'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nazwa'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGearModels()
    {
        return $this->hasMany(\common\models\GearModel::className(), ['company_id' => 'id']);
    }




}
