<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "gear_model_attachment".
 *
 * @property integer $id
 * @property string $filename
 * @property string $extension
 * @property integer $type
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $gear_model_id
 * @property string $mime_type
 * @property string $base_name
 * @property string $info
 *
 * @property \common\models\GearModel $gearModel
 * @property string $aliasModel
 */
abstract class GearModelAttachment extends \common\components\BaseActiveRecord
{


    public static function getDb() {
        return Yii::$app->db2;
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gear_model_attachment';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'status', 'gear_model_id'], 'integer'],
            [['create_time', 'update_time'], 'safe'],
            [['info'], 'string'],
            [['filename', 'mime_type', 'base_name'], 'string', 'max' => 255],
            [['extension'], 'string', 'max' => 255],
            [['gear_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearModel::className(), 'targetAttribute' => ['gear_model_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'filename' => Yii::t('app', 'Nazwa pliku'),
            'extension' => Yii::t('app', 'Rozszerzenie'),
            'type' => Yii::t('app', 'Typ'),
            'status' => Yii::t('app', 'Status'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'gear_model_id' => Yii::t('app', 'ID modelu'),
            'mime_type' => Yii::t('app', 'Typ Mime'),
            'base_name' => Yii::t('app', 'Nazwa podstawowa'),
            'info' => Yii::t('app', 'Info'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGearModel()
    {
        return $this->hasOne(\common\models\GearModel::className(), ['id' => 'gear_model_id']);
    }




}
