<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "incomes_gear_outer".
 *
 * @property integer $id
 * @property integer $income_id
 * @property integer $outer_gear_id
 * @property integer $gear_quantity
 *
 * @property \common\models\IncomesWarehouse $income
 * @property \common\models\OuterGear $outerGear
 * @property string $aliasModel
 */
abstract class IncomesGearOuter extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'incomes_gear_outer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['income_id', 'outer_gear_id', 'gear_quantity'], 'required'],
            [['income_id', 'outer_gear_id', 'gear_quantity'], 'integer'],
            [['income_id'], 'exist', 'skipOnError' => true, 'targetClass' => IncomesWarehouse::className(), 'targetAttribute' => ['income_id' => 'id']],
            [['outer_gear_id'], 'exist', 'skipOnError' => true, 'targetClass' => OuterGear::className(), 'targetAttribute' => ['outer_gear_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'income_id' => Yii::t('app', 'ID przyjęcia'),
            'outer_gear_id' => Yii::t('app', 'ID sprzętu zewnętrznego'),
            'gear_quantity' => Yii::t('app', 'Liczba'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIncome()
    {
        return $this->hasOne(\common\models\IncomesWarehouse::className(), ['id' => 'income_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOuterGear()
    {
        return $this->hasOne(\common\models\OuterGear::className(), ['id' => 'outer_gear_id']);
    }




}
