<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "incomes_warehouse".
 *
 * @property integer $id
 * @property integer $user
 * @property string $datetime
 * @property string $comments
 *
 * @property \common\models\IncomesForCustomer[] $incomesForCustomers
 * @property \common\models\IncomesForEvent[] $incomesForEvents
 * @property \common\models\IncomesForRent[] $incomesForRents
 * @property \common\models\IncomesGearOur[] $incomesGearOurs
 * @property \common\models\IncomesGearOuter[] $incomesGearOuters
 * @property \common\models\User $user0
 * @property string $aliasModel
 */
abstract class IncomesWarehouse extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'incomes_warehouse';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user', 'datetime'], 'required'],
            [['user'], 'integer'],
            [['datetime'], 'safe'],
            [['comments'], 'string'],
            [['user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user' => Yii::t('app', 'Użytkownik'),
            'datetime' => Yii::t('app', 'Data i godzina'),
            'comments' => Yii::t('app', 'Uwagi'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIncomesForCustomers()
    {
        return $this->hasMany(\common\models\IncomesForCustomer::className(), ['income_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIncomesForEvents()
    {
        return $this->hasMany(\common\models\IncomesForEvent::className(), ['income_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIncomesForRents()
    {
        return $this->hasMany(\common\models\IncomesForRent::className(), ['income_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIncomesGearOurs()
    {
        return $this->hasMany(\common\models\IncomesGearOur::className(), ['income_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIncomesGearOuters()
    {
        return $this->hasMany(\common\models\IncomesGearOuter::className(), ['income_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser0()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user']);
    }

        /**
     * @return \yii\db\ActiveQuery
     */
    public function getWarehouse()
    {
        return $this->hasOne(\common\models\Warehouse::className(), ['id' => 'warehouse_id']);
    }




}
