<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "incomes_gear_our".
 *
 * @property integer $id
 * @property integer $income_id
 * @property integer $gear_id
 * @property integer $quantity
 *
 * @property \common\models\IncomesWarehouse $income
 * @property \common\models\GearItem $gear
 * @property string $aliasModel
 */
abstract class IncomesGearOur extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'incomes_gear_our';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['income_id', 'gear_id', 'quantity'], 'required'],
            [['income_id', 'gear_id', 'quantity'], 'integer'],
            [['income_id'], 'exist', 'skipOnError' => true, 'targetClass' => IncomesWarehouse::className(), 'targetAttribute' => ['income_id' => 'id']],
            [['gear_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearItem::className(), 'targetAttribute' => ['gear_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'income_id' => Yii::t('app', 'ID przyjęcia'),
            'gear_id' => Yii::t('app', 'ID egzemplarza'),
            'quantity' => Yii::t('app', 'Liczba'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIncome()
    {
        return $this->hasOne(\common\models\IncomesWarehouse::className(), ['id' => 'income_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGear()
    {
        return $this->hasOne(\common\models\GearItem::className(), ['id' => 'gear_id']);
    }




}
