<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "invoice_serie".
 *
 * @property integer $id
 * @property string $name
 * @property integer $type
 * @property string $pattern
 * @property integer $start_number
 * @property string $reset_number_period
 *
 * @property \common\models\Invoice[] $invoices
 * @property string $aliasModel
 */
abstract class InvoiceSerie extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoice_serie';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'pattern'], 'required'],
            [['type', 'start_number'], 'integer'],
            [['name', 'pattern', 'reset_number_period'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nazwa'),
            'type' => Yii::t('app', 'Typ dokumentu'),
            'pattern' => Yii::t('app', 'Wzorzec'),
            'start_number' => Yii::t('app', 'Numer początkowy'),
            'reset_number_period' => Yii::t('app', 'Resetowanie numeru'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoices()
    {
        return $this->hasMany(\common\models\Invoice::className(), ['series_id' => 'id']);
    }




}
