<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "invoice_type_default_series".
 *
 * @property integer $id
 * @property integer $invoice_type
 * @property integer $series_id
 *
 * @property \common\models\InvoiceSerie $series
 * @property string $aliasModel
 */
abstract class InvoiceTypeDefaultSeries extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoice_type_default_series';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['invoice_type', 'series_id'], 'required'],
            [['invoice_type', 'series_id'], 'integer'],
            [['series_id'], 'exist', 'skipOnError' => true, 'targetClass' => InvoiceSerie::className(), 'targetAttribute' => ['series_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'invoice_type' => 'Invoice Type',
            'series_id' => 'Series ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSeries()
    {
        return $this->hasOne(\common\models\InvoiceSerie::className(), ['id' => 'series_id']);
    }




}
