<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "language".
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property integer $sort_order
 * @property string $aliasModel
 */
abstract class Language extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'language';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'name'], 'required'],
            [['sort_order'], 'integer'],
            [['code', 'name'], 'string', 'max' => 255],
            [['code'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'code' => Yii::t('app', 'Kod'),
            'name' => Yii::t('app', 'Nazwa'),
            'sort_order' => Yii::t('app', 'Kolejność'),
        ];
    }




}
