<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "location_attachment".
 *
 * @property integer $id
 * @property string $filename
 * @property string $extension
 * @property integer $type
 * @property integer $status
 * @property string $content
 * @property string $create_time
 * @property string $update_time
 * @property string $info
 * @property integer $location_id
 * @property string $mime_type
 * @property string $base_name
 *
 * @property \common\models\Location $location
 * @property string $aliasModel
 */
abstract class LocationAttachment extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_attachment';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'status', 'location_id'], 'integer'],
            [['content', 'info'], 'string'],
            [['create_time', 'update_time'], 'safe'],
            [['filename', 'extension', 'mime_type', 'base_name'], 'string', 'max' => 255],
            [['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => Location::className(), 'targetAttribute' => ['location_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'filename' => Yii::t('app', 'Plik'),
            'extension' => Yii::t('app', 'Rozszerzenie'),
            'type' => Yii::t('app', 'Typ'),
            'status' => Yii::t('app', 'Status'),
            'content' => Yii::t('app', 'Zawartość'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'info' => Yii::t('app', 'Info'),
            'location_id' => Yii::t('app', 'Miejsce'),
            'mime_type' => Yii::t('app', 'Typ Mime'),
            'base_name' => Yii::t('app', 'Nazwa podstawowa'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'location_id']);
    }




}
