<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "location".
 *
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property string $city
 * @property string $zip
 * @property string $country
 * @property string $info
 * @property string $latitude
 * @property string $longitude
 * @property string $create_time
 * @property string $update_time
 * @property integer $type
 * @property integer $status
 * @property string $travel_time
 * @property string $manager_phone
 * @property string $electrician_phone
 * @property string $distance
 * @property string $photo
 * @property string $rent_price
 * @property integer $owner_id
 * @property string $video
 * @property integer $active
 *
 * @property \common\models\Event[] $events
 * @property \common\models\LocationAttachment[] $locationAttachments
 * @property \common\models\Offer[] $offers
 * @property string $aliasModel
 */
abstract class Location extends \common\components\BaseActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location';
    }

    public static function getDb() {
        return Yii::$app->db2;
    }

     public static function find()
    {
        return new LocationQuery(get_called_class());
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['info','description'], 'string'],
            [['latitude', 'longitude', 'distance', 'rent_price'], 'number'],
            [['create_time', 'update_time'], 'safe'],
            [['type', 'status', 'owner_id', 'province_id', 'beds', 'biggest_room', 'stars', 'location_type_id', 'active', 'public', 'country_id'], 'integer'],
            [['name', 'address', 'city', 'zip', 'country', 'travel_time', 'manager_phone', 'electrician_phone', 'photo', 'video', 'website', 'email'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nazwa'),
            'address' => Yii::t('app', 'Adres'),
            'city' => Yii::t('app', 'Miasto'),
            'zip' => Yii::t('app', 'Kod pocztowy'),
            'country' => Yii::t('app', 'Kraj'),
            'info' => Yii::t('app', 'Informacje'),
            'latitude' => Yii::t('app', 'Szerokość'),
            'longitude' => Yii::t('app', 'Długość'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'type' => Yii::t('app', 'Typ'),
            'status' => Yii::t('app', 'Status'),
            'travel_time' => Yii::t('app', 'Średni czas dojazdu'),
            'manager_phone' => Yii::t('app', 'Numer kontaktowy'),
            'electrician_phone' => Yii::t('app', 'Numer elektryka'),
            'distance' => Yii::t('app', 'Odległość od magazynu'),
            'photo' => Yii::t('app', 'Zdjęcie'),
            'rent_price' => Yii::t('app', 'Cena wynajmu'),
            'owner_id' => Yii::t('app', 'Właściciel'),
            'video' => Yii::t('app', 'ID filmu na youtubie'),
            'description' => Yii::t('app', 'Opis'),
            'stars' => Yii::t('app', 'Gwiazdki'),
            'website' => Yii::t('app', 'Strona internetowa'),
            'email' => Yii::t('app', 'Adres e-mail'),
            'biggest_room' => Yii::t('app', 'Największa sala konferencyjna'),
            'beds' => Yii::t('app', 'Miejsca noclegowe'),
            'province_id' => Yii::t('app', 'Województwo'),
            'location_type_id'=>Yii::t('app', 'Typ obiektu'),
            'public'=>Yii::t('app', 'Publiczne'),
            'country_id' => Yii::t('app', 'Kraj'),
            'owner'=>Yii::t('app', 'Udostępnił')
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents() 
    { 
        return $this->hasMany(\common\models\Event::className(), ['location_id' => 'id']);
    } 
         
    /** 
     * @return \yii\db\ActiveQuery 
     */ 
    public function getLocationAttachments() 
    { 
        return $this->hasMany(\common\models\LocationAttachment::className(), ['location_id' => 'id']);
    } 
         
    /** 
     * @return \yii\db\ActiveQuery 
     */ 
    public function getLocationPanoramas() 
    { 
        return $this->hasMany(\common\models\LocationPanorama::className(), ['location_id' => 'id']);
    } 
         
    /** 
     * @return \yii\db\ActiveQuery 
     */ 
    public function getLocationPhotos() 
    { 
        return $this->hasMany(\common\models\LocationPhoto::className(), ['location_id' => 'id']);
    } 
         
    /** 
     * @return \yii\db\ActiveQuery 
     */ 
    public function getLocationPlans() 
    { 
        return $this->hasMany(\common\models\LocationPlan::className(), ['location_id' => 'id']);
    } 
       /**
    * @return \yii\db\ActiveQuery
    */
   public function getLocationNotes()
   {
       return $this->hasMany(\common\models\LocationNote::className(), ['location_id' => 'id']);
   }

   public function getLocationType()
   {
       return $this->hasOne(\common\models\LocationType::className(), ['id' => 'location_type_id']);
   }
 
    public function getProvince()
   {
       return $this->hasOne(\common\models\Province::className(), ['id' => 'province_id']);
   }        
    /** 
     * @return \yii\db\ActiveQuery 
     */ 
    public function getOffers() 
    { 
        return $this->hasMany(\common\models\Offer::className(), ['location_id' => 'id']);
    } 
         
    /** 
     * @return \yii\db\ActiveQuery 
     */ 
    public function getRooms() 
    { 
        return $this->hasMany(\common\models\Room::className(), ['location_id' => 'id']);
    } 

    public function isEditable()
    {
        if ($this->public<2)
            return true;
        else
            return false;
    }



}
