<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "meeting_mail_reminder".
 *
 * @property integer $id
 * @property integer $meeting_id
 * @property integer $mail_id
 *
 * @property \common\models\Meeting $meeting
 * @property \common\models\NotificationMail $mail
 * @property string $aliasModel
 */
abstract class MeetingMailReminder extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'meeting_mail_reminder';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['meeting_id', 'mail_id'], 'required'],
            [['meeting_id', 'mail_id'], 'integer'],
            [['meeting_id'], 'exist', 'skipOnError' => true, 'targetClass' => Meeting::className(), 'targetAttribute' => ['meeting_id' => 'id']],
            [['mail_id'], 'exist', 'skipOnError' => true, 'targetClass' => NotificationMail::className(), 'targetAttribute' => ['mail_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' =>  Yii::t('app', 'ID'),
            'meeting_id' =>  Yii::t('app', 'ID spotkania'),
            'mail_id' =>  Yii::t('app', 'ID maila'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeeting()
    {
        return $this->hasOne(\common\models\Meeting::className(), ['id' => 'meeting_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMail()
    {
        return $this->hasOne(\common\models\NotificationMail::className(), ['id' => 'mail_id']);
    }




}
