<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "mobile_qr_scan".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $type
 * @property integer $gear_id
 * @property string $created_at
 *
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class MobileQrScan extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mobile_qr_scan';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'type', 'gear_id'], 'required'],
            [['user_id', 'type', 'gear_id'], 'integer'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'ID użytkownikaD'),
            'type' => Yii::t('app', 'typ'),
            'gear_id' => Yii::t('app', 'ID sprzętu'),
            'created_at' => Yii::t('app', 'Data dodania'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }




}
