<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "notification_mail".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $subject
 * @property string $text
 * @property string $sending_time
 * @property string $email_address
 * @property integer $sent
 *
 * @property \common\models\User $user
 * @property \common\models\MeetingMailReminder[] $meetingMailReminders
 * @property \common\models\VehicleOcMailReminder[] $vehicleOcMailReminders
 * @property string $aliasModel
 */
abstract class NotificationMail extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'notification_mail';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'subject', 'text', 'sending_time', 'email_address'], 'required'],
            [['user_id', 'sent'], 'integer'],
            [['sending_time'], 'safe'],
            [['subject', 'text', 'email_address'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' =>  Yii::t('app', 'ID'),
            'user_id' =>  Yii::t('app', 'ID użytkownika'),
            'subject' =>  Yii::t('app', 'Temat'),
            'text' =>  Yii::t('app', 'Tekst'),
            'sending_time' =>  Yii::t('app', 'Data wysłania'),
            'email_address' =>  Yii::t('app', 'Adres e-mail'),
            'sent' =>  Yii::t('app', 'Wysłano'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeetingMailReminders()
    {
        return $this->hasMany(\common\models\MeetingMailReminder::className(), ['mail_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicleOcMailReminders()
    {
        return $this->hasMany(\common\models\VehicleOcMailReminder::className(), ['mail_id' => 'id']);
    }

}
