<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "notification_sms".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $text
 * @property string $sms_id
 * @property string $sending_time
 *
 * @property \common\models\User $user
 * @property \common\models\MeetingSmsReminder[] $meetingSmsReminders
 * @property \common\models\VehicleOcSmsReminder[] $vehicleOcSmsReminders
 * @property string $aliasModel
 */
abstract class NotificationSms extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'notification_sms';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'text', 'sending_time'], 'required'],
            [['user_id'], 'integer'],
            [['sending_time'], 'safe'],
            [['text', 'sms_id'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' =>  Yii::t('app', 'ID'),
            'user_id' =>  Yii::t('app', 'ID użytkownika'),
            'text' =>  Yii::t('app', 'Tekst'),
            'sms_id' =>  Yii::t('app', 'ID smsa'),
            'sending_time' =>  Yii::t('app', 'Data wysłania'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeetingSmsReminders()
    {
        return $this->hasMany(\common\models\MeetingSmsReminder::className(), ['sms_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicleOcSmsReminders()
    {
        return $this->hasMany(\common\models\VehicleOcSmsReminder::className(), ['sms_id' => 'id']);
    }
}
