<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "offer_vehicle".
 *
 * @property integer $offer_id
 * @property integer $vehicle_id
 * @property integer $quantity
 * @property string $price
 * @property integer $price_type
 * @property integer $distance
 *
 * @property \common\models\Offer $offer
 * @property \common\models\Vehicle $vehicle
 * @property string $aliasModel
 */
abstract class OfferVehicle extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_vehicle';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'vehicle_id', 'quantity'], 'required'],
            [['offer_id', 'vehicle_id', 'quantity', 'price_type', 'type', 'vehicle_price_id'], 'integer'],
            [['price', 'distance', 'cost', 'vat_rate'], 'number'],
            [['description', 'unit'], 'string'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['vehicle_id'], 'exist', 'skipOnError' => true, 'targetClass' => VehicleModel::className(), 'targetAttribute' => ['vehicle_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'offer_id' => Yii::t('app', 'ID oferty'),
            'vehicle_id' => Yii::t('app', 'ID pojazdu'),
            'quantity' => Yii::t('app', 'Ilość'),
            'price' => Yii::t('app', 'Cena'),
            'price_type' => Yii::t('app', 'Typ ceny'),
            'distance' => Yii::t('app', 'Odległość'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicle()
    {
        return $this->hasOne(\common\models\VehicleModel::className(), ['id' => 'vehicle_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehiclePrice()
    {
        return $this->hasOne(\common\models\VehiclePrice::className(), ['id' => 'vehicle_price_id']);
    }

}
