<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "offer_role".
 *
 * @property integer $offer_id
 * @property integer $role_id
 * @property integer $duration
 * @property string $price
 * @property integer $quantity
 * @property string $create_time
 * @property string $update_time
 * @property integer $status
 * @property integer $type
 *
 * @property \common\models\Offer $offer
 * @property \common\models\UserEventRole $role
 * @property string $aliasModel
 */
abstract class OfferRole extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_role';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'role_id', 'time_type'], 'required'],
            [['quantity', 'offer_id', 'role_id',  'status', 'type', 'time_type', 'salary_type', 'role_price_id'], 'integer'],
            [['duration', 'price', 'cost', 'cost_hour', 'vat_rate'], 'number'],
            [['description', 'unit'], 'string'],
            [['create_time', 'update_time'], 'safe'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['role_id'], 'exist', 'skipOnError' => true, 'targetClass' => UserEventRole::className(), 'targetAttribute' => ['role_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'offer_id' => Yii::t('app', 'ID oferty'),
            'role_id' => Yii::t('app', 'ID roli'),
            'duration' => Yii::t('app', 'Liczba dni'),
            'price' => Yii::t('app', 'Cena'),
            'quantity' => Yii::t('app', 'Ilość'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'status' => Yii::t('app', 'Status'),
            'type' => Yii::t('app', 'Typ'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRole()
    {
        return $this->hasOne(\common\models\UserEventRole::className(), ['id' => 'role_id']);
    }


    public static function getTimeType()
    {
        return[
        1=>Yii::t('app', 'Pakowanie'),
        2=>Yii::t('app', 'Montaż'),
        3=>Yii::t('app', 'Event'),
        4=>Yii::t('app', 'Demontaż'),
        ];            
    }



}
