<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "offer_outer_gear".
 *
 * @property integer $offer_id
 * @property integer $outer_gear_id
 * @property integer $quantity
 * @property integer $discount
 * @property integer $duration
 * @property integer $first_day_percent
 * @property string $price
 *
 * @property \common\models\Offer $offer
 * @property \common\models\OuterGear $outerGear
 * @property string $aliasModel
 */
abstract class OfferOuterGear extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_outer_gear';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'outer_gear_model_id'], 'required'],
            [['quantity', 'duration', 'price', 'vat_rate'], 'number'],
            ['description', 'string'],
            [['offer_id', 'outer_gear_model_id',  'discount',  'first_day_percent', 'type', 'gears_price_id'], 'integer'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['outer_gear_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => OuterGearModel::className(), 'targetAttribute' => ['outer_gear_model_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'offer_id' => Yii::t('app', 'ID oferty'),
            'outer_gear_model_id' => Yii::t('app', 'ID sprzętu zewnętrznego'),
            'quantity' => Yii::t('app', 'Liczba'),
            'discount' => Yii::t('app', 'Rabat'),
            'duration' => Yii::t('app', 'Liczba dni'),
            'first_day_percent' => Yii::t('app', 'Procent dnia pierwszego'),
            'price' => Yii::t('app', 'Cena'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOuterGearModel()
    {
        return $this->hasOne(\common\models\OuterGearModel::className(), ['id' => 'outer_gear_model_id']);
    }

    public function getGearsPrice()
    {
        return $this->hasOne(\common\models\GearsPrice::className(), ['id' => 'gears_price_id']);
    }


}
