<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "offer_gear".
 *
 * @property integer $offer_id
 * @property integer $gear_id
 * @property integer $quantity
 * @property integer $discount
 * @property integer $duration
 * @property integer $first_day_percent
 * @property string $price
 *
 * @property \common\models\Offer $offer
 * @property \common\models\Gear $gear
 * @property string $aliasModel
 */
abstract class OfferGear extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_gear';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'gear_id'], 'required'],
            [['description'], 'string'],
            [['duration','price', 'vat_rate','quantity',  'discount',  'first_day_percent'], 'number'],
            [['offer_id', 'gear_id', 'type', 'gears_price_id', 'offer_gear_id', 'offer_group_id', 'offer_outer_gear_id'], 'integer'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['gear_id'], 'exist', 'skipOnError' => true, 'targetClass' => Gear::className(), 'targetAttribute' => ['gear_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'offer_id' => Yii::t('app', 'ID oferty'),
            'gear_id' => Yii::t('app', 'ID modelu sprzętu'),
            'quantity' => Yii::t('app', 'Ilość'),
            'discount' => Yii::t('app', 'Rabat'),
            'duration' => Yii::t('app', 'Liczba dni'),
            'first_day_percent' => Yii::t('app', 'Procent dnia pierwszego'),
            'price' => Yii::t('app', 'Cena'),
            'vat_rate' => Yii::t('app', 'Stawka VAT'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGear()
    {
        return $this->hasOne(\common\models\Gear::className(), ['id' => 'gear_id']);
    }


    public function getGearsPrice()
    {
        return $this->hasOne(\common\models\GearsPrice::className(), ['id' => 'gears_price_id']);
    }


}
