<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "offer_user_skills".
 *
 * @property integer $offer_id
 * @property integer $user_id
 * @property integer $skill_id
 * @property string $time_from
 * @property string $time_to
 *
 * @property \common\models\Offer $offer
 * @property \common\models\User $user
 * @property \common\models\Skill $skill
 * @property string $aliasModel
 */
abstract class OfferUserSkills extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_user_skills';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'user_id', 'skill_id', 'time_from', 'time_to'], 'required'],
            [['offer_id', 'user_id', 'skill_id'], 'integer'],
            [['time_from', 'time_to'], 'safe'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['skill_id'], 'exist', 'skipOnError' => true, 'targetClass' => Skill::className(), 'targetAttribute' => ['skill_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'offer_id' => Yii::t('app', 'Oferta'),
            'user_id' => Yii::t('app', 'Użytkownik'),
            'skill_id' => Yii::t('app', 'Umiejętnośc'),
            'time_from' => Yii::t('app', 'Czas od'),
            'time_to' => Yii::t('app', 'Czas do'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSkill()
    {
        return $this->hasOne(\common\models\Skill::className(), ['id' => 'skill_id']);
    }




}
