<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "offer_setting".
 *
 * @property integer $id
 * @property integer $offer_id
 * @property integer $category_id
 * @property integer $first_day_percent
 * @property integer $duration
 * @property integer $discount
 * @property string $create_time
 * @property string $update_time
 * @property integer $type
 *
 * @property \common\models\Offer $offer
 * @property \common\models\GearCategory $category
 * @property string $aliasModel
 */
abstract class OfferSetting extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_setting';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id'], 'required'],
            [['offer_id', 'category_id', 'first_day_percent', 'duration', 'discount', 'type'], 'integer'],
            [['create_time', 'update_time'], 'safe'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearCategory::className(), 'targetAttribute' => ['category_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'offer_id' => Yii::t('app', 'ID oferty'),
            'category_id' => Yii::t('app', 'ID kategorii'),
            'first_day_percent' => Yii::t('app', 'Procent dnia pierwszego'),
            'duration' => Yii::t('app', 'Liczba dni pracy sprzętu'),
            'discount' => Yii::t('app', 'Rabat'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'type' => Yii::t('app', 'Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\GearCategory::className(), ['id' => 'category_id']);
    }




}
