<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "offer_gear_item".
 *
 * @property integer $offer_id
 * @property integer $gear_item_id
 * @property integer $quantity
 * @property string $start_time
 * @property string $end_time
 * @property integer $type
 * @property string $create_time
 * @property string $update_time
 *
 * @property \common\models\Offer $offer
 * @property \common\models\GearItem $gearItem
 * @property string $aliasModel
 */
abstract class OfferGearItem extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_gear_item';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'gear_item_id'], 'required'],
            [['offer_id', 'gear_item_id', 'quantity', 'type'], 'integer'],
            [['start_time', 'end_time', 'create_time', 'update_time'], 'safe'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['gear_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearItem::className(), 'targetAttribute' => ['gear_item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'offer_id' => Yii::t('app', 'ID oferty'),
            'gear_item_id' => Yii::t('app', 'ID egzemplarza'),
            'quantity' => Yii::t('app', 'Liczba'),
            'start_time' => Yii::t('app', 'Początek'),
            'end_time' => Yii::t('app', 'Koniec'),
            'type' => Yii::t('app', 'Typ'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGearItem()
    {
        return $this->hasOne(\common\models\GearItem::className(), ['id' => 'gear_item_id']);
    }




}
