<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "offer_custom_items".
 *
 * @property integer $id
 * @property integer $offer_id
 * @property integer $quantity
 * @property string $name
 * @property string $price
 * @property integer $diff_count
 * @property integer $discount
 * @property integer $department_id
 *
 * @property \common\models\Offer $offer
 * @property \common\models\Department $department
 * @property string $aliasModel
 */
abstract class OfferCustomItems extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_custom_items';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'quantity', 'name', 'price', 'diff_count', 'discount'], 'required'],
            [['offer_id', 'quantity', 'diff_count', 'discount', 'department_id'], 'integer'],
            [['price', 'cost'], 'number'],
            [['name'], 'string', 'max' => 255],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['department_id'], 'exist', 'skipOnError' => true, 'targetClass' => Department::className(), 'targetAttribute' => ['department_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'offer_id' => Yii::t('app', 'Oferta'),
            'quantity' => Yii::t('app', 'Liczba szt.'),
            'name' => Yii::t('app', 'Nazwa urządzenia/usługi'),
            'price' => Yii::t('app', 'Cena'),
            'diff_count' => Yii::t('app', 'Liczba'),
            'discount' => Yii::t('app', 'Rabat %'),
            'department_id' => Yii::t('app', 'Oddział'),
            'cost' => Yii::t('app', 'Koszt')
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartment()
    {
        return $this->hasOne(\common\models\Department::className(), ['id' => 'department_id']);
    }




}
