<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "outcomes_for_customer".
 *
 * @property integer $id
 * @property integer $outcome_id
 * @property integer $customer_id
 *
 * @property \common\models\OutcomesWarehouse $outcome
 * @property \common\models\Customer $customer
 * @property string $aliasModel
 */
abstract class OutcomesForCustomer extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'outcomes_for_customer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['outcome_id', 'customer_id'], 'required'],
            [['outcome_id', 'customer_id'], 'integer'],
            [['outcome_id'], 'exist', 'skipOnError' => true, 'targetClass' => OutcomesWarehouse::className(), 'targetAttribute' => ['outcome_id' => 'id']],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Customer::className(), 'targetAttribute' => ['customer_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'outcome_id' => Yii::t('app', 'ID wydania z magazynu'),
            'customer_id' => Yii::t('app', 'ID klienta'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOutcome()
    {
        return $this->hasOne(\common\models\OutcomesWarehouse::className(), ['id' => 'outcome_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\common\models\Customer::className(), ['id' => 'customer_id']);
    }




}
