<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "outcomes_gear_our".
 *
 * @property integer $id
 * @property integer $outcome_id
 * @property integer $gear_id
 * @property integer $gear_quantity
 *
 * @property \common\models\OutcomesWarehouse $outcome
 * @property \common\models\GearItem $gear
 * @property string $aliasModel
 */
abstract class OutcomesGearOur extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'outcomes_gear_our';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['outcome_id', 'gear_id', 'gear_quantity'], 'required'],
            [['outcome_id', 'gear_id', 'gear_quantity'], 'integer'],
            [['outcome_id'], 'exist', 'skipOnError' => true, 'targetClass' => OutcomesWarehouse::className(), 'targetAttribute' => ['outcome_id' => 'id']],
            [['gear_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearItem::className(), 'targetAttribute' => ['gear_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'outcome_id' => Yii::t('app', 'ID wydania z magazynu'),
            'gear_id' => Yii::t('app', 'ID modelu sprzętu'),
            'gear_quantity' => Yii::t('app', 'Liczba'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOutcome()
    {
        return $this->hasOne(\common\models\OutcomesWarehouse::className(), ['id' => 'outcome_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGear()
    {
        return $this->hasOne(\common\models\GearItem::className(), ['id' => 'gear_id']);
    }




}
