<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "outer_gear_item".
 *
 * @property integer $id
 * @property string $name
 * @property string $photo
 * @property string $weight
 * @property string $width
 * @property string $height
 * @property string $depth
 * @property string $weight_case
 * @property string $height_case
 * @property string $depth_case
 * @property string $width_case
 * @property string $volume
 * @property string $warehouse
 * @property string $location
 * @property string $code
 * @property string $serial
 * @property string $lamp_hours
 * @property string $description
 * @property string $info
 * @property string $purchase_price
 * @property string $refund_amount
 * @property string $test_date
 * @property string $tester
 * @property string $test_status
 * @property string $service
 * @property integer $outer_gear_id
 * @property integer $status
 * @property integer $type
 * @property string $create_time
 * @property string $update_time
 * @property integer $group_id
 * @property integer $number
 *
 * @property \common\models\OuterGear $outerGear
 * @property \common\models\GearGroup $group
 * @property string $aliasModel
 */
abstract class OuterGearItem extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'outer_gear_item';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'outer_gear_id'], 'required'],
            [['weight', 'width', 'height', 'depth', 'weight_case', 'height_case', 'depth_case', 'width_case', 'volume', 'lamp_hours', 'purchase_price', 'refund_amount'], 'number'],
            [['description', 'info', 'service'], 'string'],
            [['test_date', 'create_time', 'update_time'], 'safe'],
            [['outer_gear_id', 'status', 'type', 'group_id', 'number'], 'integer'],
            [['name', 'photo', 'warehouse', 'location', 'code', 'serial', 'tester', 'test_status'], 'string', 'max' => 255],
            [['outer_gear_id'], 'exist', 'skipOnError' => true, 'targetClass' => OuterGear::className(), 'targetAttribute' => ['outer_gear_id' => 'id']],
            [['group_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearGroup::className(), 'targetAttribute' => ['group_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nazwa'),
            'photo' => Yii::t('app', 'Zdjęcie'),
            'weight' => Yii::t('app', 'Waga'),
            'width' => Yii::t('app', 'Szerokość'),
            'height' => Yii::t('app', 'Wysokość'),
            'depth' => Yii::t('app', 'Głębokość'),
            'weight_case' => Yii::t('app', 'Waga z case'),
            'height_case' => Yii::t('app', 'Wysokość case'),
            'depth_case' => Yii::t('app', 'Głębokość case'),
            'width_case' => Yii::t('app', 'Szerokość case'),
            'volume' => Yii::t('app', 'Objętość'),
            'warehouse' => Yii::t('app', 'Magazyn'),
            'location' => Yii::t('app', 'Miejsce w magazynie'),
            'code' => Yii::t('app', 'Kod urządzenia'),
            'serial' => Yii::t('app', 'Numer seryjny'),
            'lamp_hours' => Yii::t('app', 'Aktualne godziny lamp'),
            'description' => Yii::t('app', 'Opis'),
            'info' => Yii::t('app', 'Uwagi'),
            'purchase_price' => Yii::t('app', 'Cena zakupu'),
            'refund_amount' => Yii::t('app', 'Kwota zwrotu'),
            'test_date' => Yii::t('app', 'Sprawdzony'),
            'tester' => Yii::t('app', 'Sprawdzający'),
            'test_status' => Yii::t('app', 'Status'),
            'service' => Yii::t('app', 'Akcje serwisowe'),
            'outer_gear_id' => Yii::t('app', 'Model'),
            'status' => Yii::t('app', 'Status'),
            'type' => Yii::t('app', 'Typ'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'group_id' => Yii::t('app', 'Zestaw'),
            'number' => Yii::t('app', 'Numer urządzenia'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOuterGear()
    {
        return $this->hasOne(\common\models\OuterGear::className(), ['id' => 'outer_gear_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(\common\models\GearGroup::className(), ['id' => 'group_id']);
    }




}
