<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "outer_gear".
 *
 * @property integer $id
 * @property string $name
 * @property integer $quantity
 * @property string $brightness
 * @property string $power_consumption
 * @property integer $status
 * @property integer $type
 * @property integer $category_id
 * @property string $width
 * @property string $height
 * @property string $volume
 * @property string $depth
 * @property string $weight
 * @property string $info
 * @property string $photo
 * @property string $create_time
 * @property string $update_time
 * @property string $price
 * @property string $selling_price
 * @property integer $sort_order
 * @property string $company_name
 * @property integer $active
 *
 * @property \common\models\EventOuterGear[] $eventOuterGears
 * @property \common\models\Event[] $events
 * @property \common\models\IncomesGearOuter[] $incomesGearOuters
 * @property \common\models\OfferOuterGear[] $offerOuterGears
 * @property \common\models\Offer[] $offers
 * @property \common\models\OutcomesGearOuter[] $outcomesGearOuters
 * @property \common\models\GearCategory $category
 * @property \common\models\OuterGearItem[] $outerGearItems
 * @property string $aliasModel
 */
abstract class OuterGear extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'outer_gear';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['outer_gear_model_id', 'company_id'], 'required'],
            [['quantity', 'active', 'company_id'], 'integer'],
            [['price', 'selling_price'], 'number'],
            [['create_time', 'update_time'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nazwa'),
            'quantity' => Yii::t('app', 'Sztuk na stanie'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'price' => Yii::t('app', 'Cena wypożyczenia'),
            'selling_price' => Yii::t('app', 'Cena Sprzedaży'),
            'company_id' => Yii::t('app', 'Firma'),
            'outer_gear_model_id' => Yii::t('app', 'Model sprzętu'),
            'photo' => Yii::t('app', 'Zdjęcie'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventOuterGears()
    {
        return $this->hasMany(\common\models\EventOuterGear::className(), ['outer_gear_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(\common\models\Event::className(), ['id' => 'event_id'])->viaTable('event_outer_gear', ['outer_gear_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIncomesGearOuters()
    {
        return $this->hasMany(\common\models\IncomesGearOuter::className(), ['outer_gear_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOfferOuterGears()
    {
        return $this->hasMany(\common\models\OfferOuterGear::className(), ['outer_gear_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffers()
    {
        return $this->hasMany(\common\models\Offer::className(), ['id' => 'offer_id'])->viaTable('offer_outer_gear', ['outer_gear_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOutcomesGearOuters()
    {
        return $this->hasMany(\common\models\OutcomesGearOuter::className(), ['outer_gear_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\GearCategory::className(), ['id' => 'category_id']);
    }

    public function getCompany()
    {
        return $this->hasOne(\common\models\Customer::className(), ['id' => 'company_id']);
    }

    public function getOuterGearModel()
    {
        return $this->hasOne(\common\models\OuterGearModel::className(), ['id' => 'outer_gear_model_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOuterGearItems()
    {
        return $this->hasMany(\common\models\OuterGearItem::className(), ['outer_gear_id' => 'id']);
    }




}
