<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "rent_gear_item".
 *
 * @property integer $rent_id
 * @property integer $gear_item_id
 * @property integer $quantity
 * @property string $start_time
 * @property string $end_time
 * @property integer $type
 * @property string $create_time
 * @property string $update_time
 * @property integer $planned
 *
 * @property \common\models\Rent $rent
 * @property \common\models\GearItem $gearItem
 * @property string $aliasModel
 */
abstract class RentGearItem extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rent_gear_item';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rent_id', 'gear_item_id'], 'required'],
            [['rent_id', 'gear_item_id', 'quantity', 'type', 'planned'], 'integer'],
            [['start_time', 'end_time', 'create_time', 'update_time'], 'safe'],
            [['rent_id', 'gear_item_id'], 'unique', 'targetAttribute' => ['rent_id', 'gear_item_id'], 'message' => 'The combination of Rent ID and Gear Item ID has already been taken.'],
            [['rent_id'], 'exist', 'skipOnError' => true, 'targetClass' => Rent::className(), 'targetAttribute' => ['rent_id' => 'id']],
            [['gear_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearItem::className(), 'targetAttribute' => ['gear_item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'rent_id' => Yii::t('app', 'ID wypożyczenia'),
            'gear_item_id' => Yii::t('app', 'ID egzemplarza'),
            'quantity' => Yii::t('app', 'Ilość'),
            'start_time' => Yii::t('app', 'Od'),
            'end_time' => Yii::t('app', 'Do'),
            'type' => Yii::t('app', 'Typ'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'planned' => Yii::t('app', 'Planowany'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRent()
    {
        return $this->hasOne(\common\models\Rent::className(), ['id' => 'rent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGearItem()
    {
        return $this->hasOne(\common\models\GearItem::className(), ['id' => 'gear_item_id']);
    }




}
