<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "dbo.GateReadings".
 *
 * @property integer $gr_id
 * @property integer $gate_id
 * @property string $tag_code
 * @property string $first_detection_date
 * @property string $last_detection_date
 * @property string $save_date
 * @property integer $status
 * @property integer $Lap
 * @property string $aliasModel
 */
abstract class RfidReadings extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dbo.GateReadings';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gate_id', 'tag_code', 'first_detection_date', 'last_detection_date', 'save_date', 'status'], 'required'],
            [['gate_id', 'status', 'Lap'], 'integer'],
            [['tag_code'], 'string'],
            [['first_detection_date', 'last_detection_date', 'save_date'], 'safe'],
            [['gate_id'], 'exist', 'skipOnError' => true, 'targetClass' => Gates::className(), 'targetAttribute' => ['gate_id' => 'gate_id']],
            [['gate_id'], 'exist', 'skipOnError' => true, 'targetClass' => Gates::className(), 'targetAttribute' => ['gate_id' => 'gate_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'gr_id' =>  Yii::t('app', 'ID'),
            'gate_id' =>  Yii::t('app', 'ID bramki'),
            'tag_code' =>  Yii::t('app', 'Tag kod'),
            'first_detection_date' =>  Yii::t('app', 'Pierwsza data detekcji'),
            'last_detection_date' =>  Yii::t('app', 'Ostatnia data detekcji'),
            'save_date' =>  Yii::t('app', 'Data zapisu'),
            'status' =>  Yii::t('app', 'Status'),
            'Lap' =>  Yii::t('app', 'Lap'),
        ];
    }




}
