<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "settlement_user".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $event_id
 * @property integer $year
 * @property integer $month
 * @property string $department_data
 * @property string $role_data
 * @property string $addon_data
 * @property string $allowance_data
 * @property string $working_hours_data
 * @property string $sum
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 *
 * @property \common\models\User $user
 * @property \common\models\Event $event
 * @property string $aliasModel
 */
abstract class SettlementUser extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'settlement_user';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'event_id', 'year', 'month'], 'required'],
            [['user_id', 'event_id', 'year', 'month', 'status'], 'integer'],
            [['department_data', 'role_data', 'addon_data', 'allowance_data', 'working_hours_data'], 'string'],
            [['sum'], 'number'],
            [['create_time', 'update_time'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'Użytkownik'),
            'event_id' => Yii::t('app', 'Wydarzenie'),
            'year' => Yii::t('app', 'Rok'),
            'month' => Yii::t('app', 'Miesiąc'),
            'department_data' => Yii::t('app', 'Dane działów'),
            'role_data' => Yii::t('app', 'Dane ról'),
            'addon_data' => Yii::t('app', 'Dane dodatków'),
            'allowance_data' => Yii::t('app', 'Dane dodatków'),
            'working_hours_data' => Yii::t('app', 'Dane przepracowanych godzin'),
            'sum' => Yii::t('app', 'Suma'),
            'status' => Yii::t('app', 'Status'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }




}
