<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "settings".
 *
 * @property integer $id
 * @property string $type
 * @property string $section
 * @property string $key
 * @property string $value
 * @property integer $active
 * @property string $created
 * @property string $modified
 * @property string $aliasModel
 */
abstract class Settings extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'settings';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'section', 'key'], 'required'],
            [['value'], 'string'],
            [['active'], 'integer'],
            [['created', 'modified'], 'safe'],
            [['type', 'section', 'key'], 'string', 'max' => 255],
            [['section', 'key'], 'unique', 'targetAttribute' => ['section', 'key'], 'message' => 'The combination of Section and Key has already been taken.']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'type' => Yii::t('app', 'Typ'),
            'section' => Yii::t('app', 'Sekcja'),
            'key' => Yii::t('app', 'Klucz'),
            'value' => Yii::t('app', 'Wartość'),
            'active' => Yii::t('app', 'Aktywny'),
            'created' => Yii::t('app', 'Stworzono'),
            'modified' => Yii::t('app', 'Zaktualizowano'),
        ];
    }




}
