<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "user_event_role".
 *
 * @property integer $id
 * @property string $name
 * @property string $salary
 * @property string $salary_customer
 * @property string $create_time
 * @property string $update_time
 * @property integer $compatibility
 *
 * @property \common\models\AddonRateRole[] $addonRateRoles
 * @property \common\models\EventUserRole[] $eventUserRoles
 * @property \common\models\EventUser[] $eventUsers
 * @property \common\models\EventUserWorkingTime[] $eventUserWorkingTimes
 * @property \common\models\EventWorkingTimeRole[] $eventWorkingTimeRoles
 * @property \common\models\EventUserWorkingTime[] $workingTimes
 * @property \common\models\OfferRole[] $offerRoles
 * @property \common\models\Offer[] $offers
 * @property \common\models\PlanboardUserEventRoleOrder[] $planboardUserEventRoleOrders
 * @property \common\models\PlanboardUserEventRoleUsersOrder[] $planboardUserEventRoleUsersOrders
 * @property \common\models\UserAddonRate[] $userAddonRates
 * @property \common\models\AddonRate[] $addonRates
 * @property string $aliasModel
 */
abstract class UserEventRole extends \common\components\BaseActiveRecord
{

        use \mootensai\relation\RelationTrait;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_event_role';
    }

    public function relationNames()
    {
        return [
            'rolePrices'
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['salary', 'salary_customer', 'salary_hours', 'salary_customer_hours'], 'number'],
            [['create_time', 'update_time'], 'safe'],
            [['compatibility', 'active', 'default_salary', 'default_salary_customer'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nazwa'),
            'salary' => Yii::t('app', 'Stawka'),
            'salary_customer' => Yii::t('app', 'Cena dla klienta'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'compatibility' => Yii::t('app', 'Wymagaj zgodności'),
            'salary_hours' => Yii::t('app', 'Stawka godzinowa'),
            'salary_customer_hours' => Yii::t('app', 'Cena dla klienta za godzinę'),
            'default_salary' => Yii::t('app', 'Domyślna stawka koszty'),
            'default_salary_customer' => Yii::t('app', 'Domyślna stawka dla klienta'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventUserRoles()
    {
        return $this->hasMany(\common\models\EventUserRole::className(), ['user_event_role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventUsers()
    {
        return $this->hasMany(\common\models\EventUser::className(), ['id' => 'event_user_id'])->viaTable('event_user_role', ['user_event_role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventUserWorkingTimes()
    {
        return $this->hasMany(\common\models\EventUserWorkingTime::className(), ['role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventWorkingTimeRoles()
    {
        return $this->hasMany(\common\models\EventWorkingTimeRole::className(), ['role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkingTimes()
    {
        return $this->hasMany(\common\models\EventUserWorkingTime::className(), ['id' => 'working_time_id'])->viaTable('event_working_time_role', ['role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOfferRoles()
    {
        return $this->hasMany(\common\models\OfferRole::className(), ['role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffers()
    {
        return $this->hasMany(\common\models\Offer::className(), ['id' => 'offer_id'])->viaTable('offer_role', ['role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanboardUserEventRoleOrders()
    {
        return $this->hasMany(\common\models\PlanboardUserEventRoleOrder::className(), ['user_event_role' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanboardUserEventRoleUsersOrders()
    {
        return $this->hasMany(\common\models\PlanboardUserEventRoleUsersOrder::className(), ['role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserAddonRates()
    {
        return $this->hasMany(\common\models\UserAddonRate::className(), ['role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRolePrices()
    {
        return $this->hasMany(\common\models\RolePrice::className(), ['role_id' => 'id']);
    }
	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getAddonRateRoles()
	{
		return $this->hasMany(\common\models\AddonRateRole::className(), ['role_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getAddonRates()
	{
		return $this->hasMany(\common\models\AddonRate::className(), ['id' => 'addon_rate_id'])->viaTable('addon_rate_role', ['role_id' => 'id']);
	}

            public function getRoleTranslates()
    {
        return $this->hasMany(\common\models\RoleTranslate::className(), ['role_id' => 'id']);
    }

}
