<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "user_addon_rate".
 *
 * @property integer $user_id
 * @property integer $rate_id
 * @property integer $role_id
 *
 * @property \common\models\User $user
 * @property \common\models\AddonRate $rate
 * @property \common\models\UserEventRole $role
 * @property string $aliasModel
 */
abstract class UserAddonRate extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_addon_rate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'rate_id', 'role_id'], 'required'],
            [['user_id', 'rate_id', 'role_id'], 'integer'],
            [['user_id', 'rate_id', 'role_id'], 'unique', 'targetAttribute' => ['user_id', 'rate_id', 'role_id'], 'message' => 'The combination of User ID, Rate ID and Role ID has already been taken.'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['rate_id'], 'exist', 'skipOnError' => true, 'targetClass' => AddonRate::className(), 'targetAttribute' => ['rate_id' => 'id']],
            [['role_id'], 'exist', 'skipOnError' => true, 'targetClass' => UserEventRole::className(), 'targetAttribute' => ['role_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => Yii::t('app', 'ID użytkownika'),
            'rate_id' => Yii::t('app', 'ID stawki'),
            'role_id' => Yii::t('app', 'ID roli'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRate()
    {
        return $this->hasOne(\common\models\AddonRate::className(), ['id' => 'rate_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRole()
    {
        return $this->hasOne(\common\models\UserEventRole::className(), ['id' => 'role_id']);
    }




}
