<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "user_notification".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property integer $sms
 * @property integer $mail
 * @property integer $push
 * @property integer $user_id
 * @property string $create_time
 * @property string $update_time
 * @property string $target_class
 * @property integer $target_id
 * @property string $info
 * @property resource $data
 *
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class UserNotification extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_notification';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content', 'info', 'data'], 'string'],
            [['sms', 'mail', 'push', 'user_id', 'target_id'], 'integer'],
            [['user_id'], 'required'],
            [['create_time', 'update_time'], 'safe'],
            [['title', 'target_class'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Temat'),
            'content' => Yii::t('app', 'Treść'),
            'sms' => Yii::t('app', 'Sms'),
            'mail' => Yii::t('app', 'E-mail'),
            'push' => Yii::t('app', 'PUSH'),
            'user_id' => Yii::t('app', 'Użytkownik'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'target_class' => Yii::t('app', 'Klasa celu'),
            'target_id' => Yii::t('app', 'ID celu'),
            'info' => Yii::t('app', 'Info'),
            'data' => Yii::t('app', 'Dane'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }




}
