<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vehicle".
 *
 * @property integer $id
 * @property string $name
 * @property string $photo
 * @property string $registration_number
 * @property string $vin_number
 * @property string $capacity
 * @property string $volume
 * @property string $fuel_consumption
 * @property string $inspection_date
 * @property string $oc_date
 * @property string $price_km
 * @property string $price_city
 * @property integer $reminder
 * @property string $price_rent
 * @property integer $type
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 * @property string $info
 * @property string $description
 * @property integer $active
 *
 * @property \common\models\EventVehicle[] $eventVehicles
 * @property \common\models\Event[] $events
 * @property \common\models\EventVehicleWorkingHours[] $eventVehicleWorkingHours
 * @property \common\models\OfferVehicle[] $offerVehicles
 * @property \common\models\Offer[] $offers
 * @property \common\models\PlanboardVehicleOrder[] $planboardVehicleOrders
 * @property \common\models\VehicleAttachment[] $vehicleAttachments
 * @property \common\models\VehicleUserRemind[] $vehicleUserReminds
 * @property \common\models\NotificationSms[] $notificationSmses
 * @property \common\models\NotificationMail[] $notificationMails
 * @property \common\models\User[] $users
 * @property string $aliasModel
 */
abstract class Vehicle extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vehicle';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['capacity', 'volume', 'fuel_consumption', 'price_km', 'price_city', 'price_rent', 'cost_km', 'cost_city'], 'number'],
            [['inspection_date', 'oc_date', 'create_time', 'update_time'], 'safe'],
            [['reminder', 'type', 'status', 'active'], 'integer'],
            [['info', 'description'], 'string'],
            [['name', 'photo', 'registration_number', 'vin_number', 'name_in_offer'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Nazwa'),
            'photo' => Yii::t('app', 'Zdjęcie'),
            'registration_number' => Yii::t('app', 'Numer rejestracyjny'),
            'vin_number' => Yii::t('app', 'Numer VIN'),
            'capacity' => Yii::t('app', 'Ładowność'),
            'volume' => Yii::t('app', 'Pojemność'),
            'fuel_consumption' => Yii::t('app', 'Średnie spalanie'),
            'inspection_date' => Yii::t('app', 'Data przeglądu'),
            'oc_date' => Yii::t('app', 'OC ważne do'),
            'price_km' => Yii::t('app', 'Cena za km'),
            'price_city' => Yii::t('app', 'Cena ryczałt w mieście'),
            'reminder' => Yii::t('app', 'Przypomnij przed końcem OC i przeglądu'),
            'price_rent' => Yii::t('app', 'Cena wynajmu za dzień'),
            'type' => Yii::t('app', 'Typ'),
            'status' => Yii::t('app', 'Status'),
            'create_time' => Yii::t('app', 'Stworzono'),
            'update_time' => Yii::t('app', 'Zaktualizowano'),
            'info' => Yii::t('app', 'Uwagi'),
            'description' => Yii::t('app', 'Opis'),
            'name_in_offer' => Yii::t('app', 'Nazwa w ofercie'),
            'cost_km' => Yii::t('app', 'Średni koszt kilometra'),
            'cost_city' => Yii::t('app', 'Średni koszt przy ryczałcie'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventVehicles()
    {
        return $this->hasMany(\common\models\EventVehicle::className(), ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(\common\models\Event::className(), ['id' => 'event_id'])->viaTable('event_vehicle', ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventVehicleWorkingHours()
    {
        return $this->hasMany(\common\models\EventVehicleWorkingHours::className(), ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOfferVehicles()
    {
        return $this->hasMany(\common\models\OfferVehicle::className(), ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffers()
    {
        return $this->hasMany(\common\models\Offer::className(), ['id' => 'offer_id'])->viaTable('offer_vehicle', ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanboardVehicleOrders()
    {
        return $this->hasMany(\common\models\PlanboardVehicleOrder::className(), ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicleAttachments()
    {
        return $this->hasMany(\common\models\VehicleAttachment::className(), ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicleServices()
    {
        return $this->hasMany(\common\models\VehicleService::className(), ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicleUserReminds()
    {
        return $this->hasMany(\common\models\VehicleUserRemind::className(), ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(\common\models\User::className(), ['id' => 'user_id'])->viaTable('vehicle_user_remind', ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNotificationSmses()
    {
        return $this->hasMany(\common\models\NotificationSms::className(), ['id' => 'sms_id'])->viaTable('vehicle_oc_sms_reminder', ['vehicle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNotificationMails()
    {
        return $this->hasMany(\common\models\NotificationMail::className(), ['id' => 'mail_id'])->viaTable('vehicle_oc_mail_reminder', ['vehicle_id' => 'id']);
    }

        public function getVehicleTranslates()
    {
        return $this->hasMany(\common\models\VehicleTranslate::className(), ['vehicle_id' => 'id']);
    }
}
