<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vehicle_oc_sms_reminder".
 *
 * @property integer $id
 * @property integer $vehicle_id
 * @property integer $sms_id
 *
 * @property \common\models\Vehicle $vehicle
 * @property \common\models\NotificationSms $sms
 * @property string $aliasModel
 */
abstract class VehicleOcSmsReminder extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vehicle_oc_sms_reminder';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vehicle_id', 'sms_id'], 'required'],
            [['vehicle_id', 'sms_id'], 'integer'],
            [['vehicle_id'], 'exist', 'skipOnError' => true, 'targetClass' => Vehicle::className(), 'targetAttribute' => ['vehicle_id' => 'id']],
            [['sms_id'], 'exist', 'skipOnError' => true, 'targetClass' => NotificationSms::className(), 'targetAttribute' => ['sms_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' =>  Yii::t('app', 'ID'),
            'vehicle_id' =>  Yii::t('app', 'ID pojazdu'),
            'sms_id' =>  Yii::t('app', 'ID smsa'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicle()
    {
        return $this->hasOne(\common\models\Vehicle::className(), ['id' => 'vehicle_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSms()
    {
        return $this->hasOne(\common\models\NotificationSms::className(), ['id' => 'sms_id']);
    }




}
