<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vehicle_oc_mail_reminder".
 *
 * @property integer $id
 * @property integer $vehicle_id
 * @property integer $mail_id
 *
 * @property \common\models\Vehicle $vehicle
 * @property \common\models\NotificationMail $mail
 * @property string $aliasModel
 */
abstract class VehicleOcMailReminder extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vehicle_oc_mail_reminder';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vehicle_id', 'mail_id'], 'required'],
            [['vehicle_id', 'mail_id'], 'integer'],
            [['vehicle_id'], 'exist', 'skipOnError' => true, 'targetClass' => Vehicle::className(), 'targetAttribute' => ['vehicle_id' => 'id']],
            [['mail_id'], 'exist', 'skipOnError' => true, 'targetClass' => NotificationMail::className(), 'targetAttribute' => ['mail_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' =>  Yii::t('app', 'ID'),
            'vehicle_id' =>  Yii::t('app', 'ID pojazdu'),
            'mail_id' =>  Yii::t('app', 'ID maila'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicle()
    {
        return $this->hasOne(\common\models\Vehicle::className(), ['id' => 'vehicle_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMail()
    {
        return $this->hasOne(\common\models\NotificationMail::className(), ['id' => 'mail_id']);
    }




}
