<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vehicle_user_remind".
 *
 * @property integer $vehicle_id
 * @property integer $user_id
 *
 * @property \common\models\Vehicle $vehicle
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class VehicleUserRemind extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vehicle_user_remind';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vehicle_id', 'user_id'], 'required'],
            [['vehicle_id', 'user_id'], 'integer'],
            [['vehicle_id', 'user_id'], 'unique', 'targetAttribute' => ['vehicle_id', 'user_id'], 'message' => 'The combination of Vehicle ID and User ID has already been taken.'],
            [['vehicle_id'], 'exist', 'skipOnError' => true, 'targetClass' => Vehicle::className(), 'targetAttribute' => ['vehicle_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'vehicle_id' => Yii::t('app', 'ID pojazdu'),
            'user_id' => Yii::t('app', 'ID użytkownika'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicle()
    {
        return $this->hasOne(\common\models\Vehicle::className(), ['id' => 'vehicle_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }




}
