<?php
namespace backend\models;

use yii\base\Model;
use common\helpers\ArrayHelper;
use Yii;

class SendFileMail extends Model
{

    public $subject;
    public $text;
    public $users;
    public $email;
    public $email2;
    public $customer_id;
    public $contact_id;


    public function rules()
    {
        return [
            [['subject', 'text', 'email'], 'string'],
            [['subject'], 'required'],
            [['email2', 'users', 'customer_id', 'contact_id'], 'safe']

        ];
    }

        public function attributeLabels()
    {
        $labels = [
            'subject' => Yii::t('app', 'Temat'),
            'text' => Yii::t('app', 'Treść'),
	        'email' => Yii::t('app', 'Adresat'),
        ];

        return array_merge(parent::attributeLabels(), $labels);
    }


    public function beforeValidate() {
    	$this->email2 = "";
        if(empty($this->email)==false)
        {
            
            $this->email2 = explode(";",str_replace(" ", "", str_replace(",", ";", $this->email)));           
        }
        if ($this->users)
        {
            $users = \common\models\User::find()->where(['id'=>$this->users])->all();
            foreach ($users as $user)
            {
                $this->email2[] .=$user->email;
            }
        }
        if ($this->contact_id)
        {
            $users = \common\models\Contact::find()->where(['id'=>$this->contact_id])->all();
            foreach ($users as $user)
            {
                $this->email2[] .=$user->email;
            }
        }
	    return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}