<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\offers\models\base;

use common\models\GearCategory;
use common\models\Offer;
use Yii;

/**
 * This is the base-model class for table "offer_extra_item".
 *
 * @property integer $id
 * @property integer $offer_id
 * @property string $name
 * @property integer $quantity
 * @property string $price
 * @property integer $duration
 * @property integer $type
 * @property integer $discount
 *
 * @property \common\models\Offer $offer
 * @property \common\models\GearCategory $category
 * @property string $aliasModel
 */
abstract class OfferExtraItem extends \common\components\BaseActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer_extra_item';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['offer_id', 'name', 'quantity', 'price', 'duration', 'type'], 'required'],
            [['offer_id',   'category_id', 'type', 'discount', 'first_day_percent', 'time_type', 'gears_price_id'], 'integer'],
            [['discount'], 'default', 'value' => 0],
            [['price', 'duration', 'cost', 'volume', 'quantity', 'weight', 'vat_rate'], 'number'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => GearCategory::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' =>  Yii::t('app', 'ID'),
            'offer_id' =>  Yii::t('app', 'ID oferty'),
            'type' =>  Yii::t('app', 'Rodzaj'),
            'name' =>  Yii::t('app', 'Nazwa'),
            'quantity' =>  Yii::t('app', 'Ilość'),
            'price' =>  Yii::t('app', 'Cena'),
            'duration' =>  Yii::t('app', 'Dni pracy'),
            'category_id' =>  Yii::t('app', 'Kategoria'),
            'discount' =>  Yii::t('app', 'Rabat'),
            'weight' =>  Yii::t('app', 'Waga [kg]'),
            'volume' =>  Yii::t('app', 'Objętość [m3]'),
            'cost' =>  Yii::t('app', 'Koszt'),
            'time_type' => Yii::t('app', 'Etap')
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(\common\models\Offer::className(), ['id' => 'offer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(GearCategory::className(), ['id' => 'category_id']);
    }

    public function getGearsPrice()
    {
        return $this->hasOne(\common\models\GearsPrice::className(), ['id' => 'gears_price_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOfferExtraCosts()
    {
        return $this->hasMany(\common\models\OfferExtraCost::className(), ['offer_extra_item_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOfferOuterGears()
    {
        return $this->hasMany(\common\models\OfferOuterGear::className(), ['offer_group_id' => 'id']);
    }
}
